backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    preview_path: "{{fields.url}}"
    create: true
    fields:
    #meta -->
      - {label: "Title", name: "title" , widget: "string", required: true}
      - {label: "Layout", name: "type", widget: "hidden", default: "posts"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Trending", name: "trending", widget: "boolean", default: false, required: false}
      - {label: "Trending Name", name: "trendname", widget: "string", required: false}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Sub Title", name: "sub_title", widget: "string", required: false}
      - {label: "SEO Discription", name: "meta_Description", widget: "text", required: false}
      - {label: "Slug", name: "url", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modify Date", name: "updateDate", widget: "datetime"}
      - {label: "Featured Image", name: "featured_Image", widget: "image", hint: "Recommended Size: 1200x680", required: false}
      - {label: "Tags", name: "tags", widget: "relation", collection: "tags", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true, required: false}
      - {label: "Categories", name: "categories", widget: "relation", required: false, collection: "categories", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true}
      #Intro-Paragraphs -->
      - {label: "Paragraphs", name: "paragraphs", widget: "list", fields: [ {label: "Paragraph", name: "paragraph", widget: "markdown" } ] }
      #Summary & Main-Heading -->
      - {label: Summary Heading, name: product_Summary, required: false, widget: string }
      #Buying Guide
      - {label: Buying Guide Heading, name: buyingGuideHead, required: false, widget: string }
      - {label: Buying Guide, name: buyingGuide, required: false, widget: markdown }
      #Product Recommendations
      - {label: Main Haeding, name: product_Mheading, required: false, widget: string }
      - {label: "Recommendation", name: "the_products",widget: "list", required: false, fields: [
            {label: "Name/Modal", required: false, name: name, widget: string },
            {label: "NameForTOC", required: false, name: nameForTOC, widget: string },
            {label: Award, required: false, name: award, widget: string },
            {label: Product Image, required: false, name: image, widget: image },
            {label: "Affiliate Link", required: false, name: amzlink, widget: string },
            # Specifications
            {label: Specifications, name: specifications, required: false, widget: "list", fields: 
              [ {label: Specification, name: specification, widget: markdown } ] 
            },
             #Pros & Cons
            {label: Pros, name: pros, required: false, widget: "list", fields: 
              [ {label: Pro, name: pro, widget: string } ] 
            },
            {label: Cons, name: cons, required: false, widget: "list", fields: 
              [ {label: Con, name: con, widget: string } ]
            },
            #Product Paragraphs
            {label: Paragraphs, name: paragraphs, required: false, widget: "list", fields: 
             [ {label: Paragraph, name: paragraph, widget: markdown } ]
            }
      ] }
      # Below Producs
      - {label: "Conclusion", name: "conclusion", required: false, widget: "list", fields: [ {label: "Paragraph", name: "paragraph", widget: "markdown" } ] }
      #Frequently Asked Questions
      - {label: "Faqs", name: "faqs", widget: "list", required: false, fields: 
        [ {label: "Question", name: "question", widget: "string" },
          {label: "Answer", name: "answer", widget: "markdown" } 
        ] }

#KnowledgeBase Collection
  - name: "knowledge-base"
    label: "Knowledge Base"
    folder: "content/knowledge-base"
    preview_path: "{{fields.url}}"
    create: true
    fields:
      - {label: "Title", name: "title" , widget: "string", required: true}
      - {label: "Layout", name: "type", widget: "hidden", default: "knowledge-base"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Discription", name: "meta_Description", widget: "text", required: false}
      - {label: "Focus Keywords", name: "meta_Keywords", widget: "string", required: false}
      - {label: "Slug", name: "url", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modify Date", name: "updateDate", widget: "datetime"}
      - {label: "Featured Image", name: "featured_Image", widget: "image", hint: "Recommended Size: 1200x680", required: false}
      - {label: "Tags", name: "tags", widget: "relation", collection: "tags", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true, required: false}
      - {label: "Categories", name: "categories", widget: "relation", required: false, collection: "categories", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true}
      - {label: "Sub Title", name: "sub_title", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      #Frequently Asked Questions
      - {label: "Faqs", name: "faqs", widget: "list", required: false, fields: 
        [ {label: "Question", name: "question", widget: "string" },
          {label: "Answer", name: "answer", widget: "markdown" } 
        ] }

#Pages Collection
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    preview_path: "{{fields.url}}"
    create: true
    fields:
      - {label: "Title", name: "title" , widget: "string", required: true}
      - {label: "Layout", name: "type", widget: "hidden", default: "pages"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Discription", name: "meta_Description", widget: "text", required: false}
      - {label: "Slug", name: "url", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

#Categories Collection
  - name: categories
    label: Categories
    folder: data/categories/
    create: true
    extension: toml
    preview_path: "{{fields.url}}"
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name, required: false}
      - {name: seo_title, label: SEO Title, required: false}
      - {name: meta_Description, label: SEO Discription, widget: text, required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}


#Tags Collection
  - name: tags
    label: Tags
    folder: data/tags/
    preview_path: "{{fields.url}}"
    create: true
    extension: toml
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name, required: false}
      - {name: seo_title, label: SEO Title, required: false}
      - {name: meta_Description, label: SEO Discription, widget: text, required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

#Settings
  - name: settings
    label: Site Settings
    files: 
      - label: "About Site"
        name: "about"
        file: "/config.toml"
        fields:
          - { label: Site URL, name: baseURL, widget: string, required: false }
          - { label: Site Title, name: title, widget: string, required: false }
          - { label: Language, name: languageCode, widget: string, default: en-us, required: false }
          - { label: Total Post to Show on Frontpage, name: paginate, widget: string, default: 8, required: false }
          - { label: Google Analytics Code, name: googleAnalytics, widget: string, required: false }
          - { label: Disqus Shortname, name: DisqusShortname, widget: string, required: false }

      - label: "SEO Settings"
        name: "seo_settings"   
        file: "/config/_default/params.toml"
        fields:
          - {label: Site Logo, name: logo, widget: image, required: false}
          - {label: Favicon, name: icon, widget: image, hint: '128x128.', required: false}
          - {label: Extended Title, name: tagline, widget: string, required: false}    
          - {label: Contact eMail, name: contacteMail, widget: string, required: false}
          - {label: Header Text, name: headerText, widget: markdown, required: false}
          - {label: Footer Text, name: footerText, widget: markdown, required: false}
          - label: "Site Colors"
            name: "colors"
            widget: "object"
            collapsed: true
            fields:
            - { label: Main Color, name: mainColor, widget: color, enableAlpha: true, allowInput: true, required: false }
          - label: "Open Graph Meta"
            name: "open_graph"
            widget: "object"
            collapsed: true
            fields:
             - {label: Meta Description, name: meta_Description, widget: text, required: false}
             - {label: Meta Image, name: image, hint: '1920x1080', widget: image, required: false }
             - {label: Facebook Publisher, name: FacebookPublisher, widget: string, required: false}
             - {label: Facebook Author, name: FacebookAuthor, widget: string, required: false}
             - {label: Twitter Publisher, name: TwitterPublisher, widget: string, required: false}
             - {label: Twitter Author, name: TwitterAuthor, widget: string, required: false}
          - label: "Site Verifications"
            name: "verifications"
            widget: "object"
            collapsed: true
            fields:
             - {label: Google Search Console Tag, name: googleSiteVerify, widget: string, required: false}
             - {label: Bing Webmaster Tag, name: BingWebmaster, widget: string, required: false}
             - {label: Pinterest Tag, name: PinterestVerify, widget: string, required: false}
             - {label: Yandex Tag, name: YandexVerify, widget: string, required: false}
          - label: "Author"
            name: "Author"
            widget: "object"
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string, required: false}
              - { label: Author Avatar, name: avatar, widget: image, required: false}   
              - { label: Author Bio, name: bio, widget: text, required: false}
              - { label: Author Facebook, name: authorFB, widget: string, required: false}
              - { label: Author Twitter, name: authortwitter, widget: string, required: false}
              - { label: Author eMail, name: authorMail, widget: string, required: false}             
          - label: "Social Media Accounts"
            name: "social_accounts"
            widget: "object"
            collapsed: true
            fields:
              - { label: Facebook, name: sitefbAccount, widget: string, required: false}
              - { label: Twitter, name: sitetwitterAccount, widget: string, required: false}
              - { label: Instagram, name: siteinstagramAccount, widget: string, required: false}
              - { label: Pinterest, name: sitepinterestAccount, widget: string, required: false}
              - { label: YouTube, name: siteYouTubeAccount, widget: string, required: false}